#!/bin/bash

# Extract name
name=$(jq -r '.name' data.json | awk '{print toupper(substr($0,1,1)) substr($0,2)}')

# Extract height (convert decimeters to meters)
height=$(jq -r '.height' data.json | awk '{printf "%.1f", $1/10}')

# Extract weight (convert hectograms to kilograms)
weight=$(jq -r '.weight' data.json | awk '{printf "%.0f", $1/10}')

# Extract type(s) (capitalize first letter)
type=$(jq -r '.types[].type.name' data.json | awk '{print toupper(substr($0,1,1)) substr($0,2)}' | paste -sd "/")

# Print in the desired format
echo "$name is of type $type, weighs ${weight}kg, and is ${height}m tall."
